### ISSUE TITLE
Added Recapture to Form in ASP.NET MVC App User can login without checking

### ISSUE THREAD

**Issue by utech626** [kdcllc/Bet.AspNetCore#124]
A user is about to login without performing recapture function:
						<div class="form-group">
							<div class="checkbox">
								<label asp-for="Input.RememberMe">
									<input asp-for="Input.RememberMe" />
									@Html.DisplayNameFor(m => m.Input.RememberMe)
								</label>
							</div>
						</div>
						**<google-recaptcha></google-recaptcha>**
						<div class="form-group">
							<button type="submit" class="btn btn-primary">Log in</button>
						</div>

**Comment by kdcllc** [comment]
@utech626 can you please provide with more details? I am using the code with no issues. The sample code would be appreciated.

**Comment by kdcllc** [comment]
@utech626 I am closing this issue.
